package ictgradschool.industry.exceptions.arraysandexceptions;

import ictgradschool.Keyboard;

import java.rmi.server.ExportException;
import java.util.Random;

/**
 * A simple program that generates an array of random numbers, then displays
 * one of them (user's choice).
 */
public class ArraysAndExceptions {


    /**
     * Runs the program.
     *
     * TODO Handle your InvalidIndexException, IndexTooLowException, and IndexTooHighException appropriately.
     */
    public void start() {

        int[] myArray = generateArray();

        // TODO Handle any exceptions generated by this line appropriately.
        // TODO If an exception is thrown, display an appropriate error message and let the user try again.
        boolean invalid = true;
        int index;
        while (invalid)
        {
            try
            {
                //throw the child class of exception
                index = getArrayIndexFromUser();
                invalid = false;
                System.out.println("The element at index " + index + " is: " + myArray[index]);
            }
            catch(Exception e)
            {
                System.out.println(e.getMessage());
                System.out.println("Please try again!");
            }
        }
    }

    /**
     * Gets an array index from the given user. Currently error-prone as it doesn't check whether the user
     * inputs valid numbers of the correct size.
     *
     * TODO Follow these steps:
     * <ol>
     *     <li>Create three new checked Exception classes (i.e. extends Exception):
     *     <ul>
     *         <li>InvalidIndexException</li>
     *         <li>IndexTooLowException</li>
     *         <li>IndexTooHighException</li>
     *     </ul>
     *     </li>
     *     <li>Declare this method to throw these three kinds of exceptions (using the throws clause)</li>
     *     <li>Throw InvalidIndexException if the user doesn't enter an integer</li>
     *     <li>Throw IndexTooLowException if the user enters an integer that's too small to be a valid index</li>
     *     <li>Throw IndexTooHighException if the user enters an integer that's too large to be a valid index</li>
     * </ol>
     */
    private int getArrayIndexFromUser() throws Exception{

        System.out.print("Enter an index: ");

        String input = Keyboard.readInput();
        int index = 0;
        try
        {
            try {
                index = Integer.parseInt(input);
            }
            catch(NumberFormatException e)
            {
                throw new InvalidIndexException("Please enter a number!");
            }

            if (index < 0)
            {
                throw new IndexTooLowException("Too low!");
            }

            if(index > 4)
            {
                throw new IndexTooHighException("Too high!");
            }
        }
        catch (IndexTooLowException e)
        {
            throw e;
        }
        catch (InvalidIndexException e)
        {
            throw e;
        }
        catch (IndexTooHighException e)
        {
            throw e;
        }

        return index;
    }

    /**
     * Creates and returns an array with five random numbers.
     */
    private int[] generateArray() {

        // TODO Create an array of length five, and fill it with random integers
        // TODO (say, between 1 - 1000, but doesn't really matter).
        int arr_length = 5;
        int[] arr_num = new int[arr_length];
        for (int i = 0; i < arr_num.length; i++)
        {
            arr_num[i] = (int)(Math.random()*10);
        }

        return arr_num;
    }

    public static void main(String[] args) {
        new ArraysAndExceptions().start();
    }

}
